### ISSUE TITLE
Level Description Box Invisible w/ Shaders Enabled

### ISSUE THREAD

**Issue by ghost** [cgytrus/MenuShaders#16]
<table cellspacing="10">
  <thead>
    <tr>
      <th scope="col">No Shaders:</th>
      <th scope="col">Shaders:</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><img src="https://github.com/user-attachments/assets/538d69fb-49de-4b80-b764-c5c172460389" width="512px" /></td>
      <td><img src="https://github.com/user-attachments/assets/d03e18be-40e9-4448-ac84-97dd76da569b" width="512px" /></td>
    </tr>
  </tbody>
</table>

**Comment by cgytrus** [comment]
this is intentional but added configuration options for that in 1.4.0

**Comment by ghost** [comment]
Thank you!!

Maybe outside the mod scope - changing the option from a toggle to an opacity input would be really cool.

**Comment by cgytrus** [comment]
i wanted to make these black semi-transparent initially but quickly realized that if one of these is too small on either dimension (like the length filter on the search screen) the corners begin clipping into each other and it looks horrible, i believe that is fixed by happy textures but im not sure if it has the ability to change these backgrounds' color/opacity, if it doesnt i will add that here, otherwise use happy textures

**Comment by ghost** [comment]
Happy Textures at least doesn't have a basic option to achieve this - it might be possible to create a texture pack that uses happy textures to accomplish this but that's a lot of work.
