### ISSUE TITLE
Shader flickering during menu transition

### ISSUE THREAD

**Issue by asterSSH** [cgytrus/MenuShaders#6]
When transitioning between menus, the background flickers in brightness (assuming as it reloads) - with fast menu enabled it becomes a lot more apparent but a lot faster as it flashes to black.

https://github.com/cgytrus/MenuShaders/assets/144290429/bb8395d9-5610-491d-97bc-875179e552fd

**Comment by cgytrus** [comment]
please, attach log files as well as the shader files, if possible.

**Comment by asterSSH** [comment]
[Geode 2024-05-16 15.19.03.log](https://github.com/cgytrus/MenuShaders/files/15339896/Geode.2024-05-16.15.19.03.log)

[menu-shader.zip](https://github.com/cgytrus/MenuShaders/files/15339900/menu-shader.zip)

**Comment by cgytrus** [comment]
ok, i was able to reproduce the issue with this specific shader, doesnt seem to happen with any other shaders for me, i will look into it

**Comment by cgytrus** [comment]
hm the effect seems to be different on my pc vs my phone
android gives the same issue as in the video
on pc its like a single frame white flicker instead
are you using an amd or intel integrated gpu?

**Comment by cgytrus** [comment]
i just realized that for me on pc the single white frame flicker is actually a single frame rendering correctly and then all proceeding frames rendering darker like in your video
no idea what this could be caused by, its probably the shader itself hitting some weird edge cases within the graphics drivers.. dont think theres anything i can do here, sorry

**Comment by cgytrus** [comment]
update:
1. it was indeed the shader
2. it is not a weird edge case but rather just a silly oversight of whoever wrote the shader, the alpha (aka opacity) being not 1 caused the weird effects
3. the fix is to add the line `gl_FragColor.w = 1.0;` at the end of main, this forces the output alpha value to always be 1
[menu-shader.zip](https://github.com/user-attachments/files/17105310/menu-shader.zip)
